// src/constants/skillOptions.js
const skillOptions = [
    { value: 'Java', label: 'Java' },
    { value: 'Spring Boot', label: 'Spring Boot' },
    { value: 'React', label: 'React' },
    { value: 'JavaScript', label: 'JavaScript' },
    { value: 'SQL', label: 'SQL' },
    { value: 'PostgreSQL', label: 'PostgreSQL' },
    { value: 'Python', label: 'Python' },
    { value: 'Flask', label: 'Flask' },
    { value: 'C++', label: 'C++' },
    { value: 'Embedded Systems', label: 'Embedded Systems' },
    { value: 'HTML', label: 'HTML' },
    { value: 'CSS', label: 'CSS' },
    { value: 'Kotlin', label: 'Kotlin' },
    { value: 'Android Development', label: 'Android Development' },
    { value: 'AWS', label: 'AWS' },
    { value: 'Docker', label: 'Docker' },
    { value: 'Machine Learning', label: 'Machine Learning' },
    { value: 'TensorFlow', label: 'TensorFlow' },
    { value: 'PHP', label: 'PHP' },
    { value: 'Laravel', label: 'Laravel' },
    { value: 'Data Analysis', label: 'Data Analysis' },
    { value: 'Ruby', label: 'Ruby' },
    { value: 'Rails', label: 'Rails' },
    { value: 'C#', label: 'C#' },
    { value: '.NET', label: '.NET' },
    { value: 'Node.js', label: 'Node.js' },
    { value: 'Rust', label: 'Rust' },
    { value: 'Blockchain', label: 'Blockchain' },
    { value: 'Django', label: 'Django' },
    { value: 'Scala', label: 'Scala' },
    { value: 'Big Data', label: 'Big Data' },
    { value: 'Vue.js', label: 'Vue.js' },
    { value: 'TypeScript', label: 'TypeScript' },
    { value: 'Go', label: 'Go' },
    { value: 'Microservices', label: 'Microservices' },
    { value: 'Perl', label: 'Perl' },
    { value: 'Shell Scripting', label: 'Shell Scripting' },
    { value: 'Kubernetes', label: 'Kubernetes' },
    { value: 'Swift', label: 'Swift' },
    { value: 'iOS Development', label: 'iOS Development' },
    { value: 'MySQL', label: 'MySQL' },
    { value: 'Hibernate', label: 'Hibernate' },
    { value: 'React.js', label: 'React.js' },
    { value: 'Redux', label: 'Redux' },
    { value: 'Azure', label: 'Azure' },
    { value: 'DevOps', label: 'DevOps' },
    { value: 'Robotics', label: 'Robotics' },
    { value: 'NLP', label: 'NLP' },
    { value: 'Oracle', label: 'Oracle' },
    { value: 'SCSS', label: 'SCSS' },
    { value: 'ASP.NET', label: 'ASP.NET' },
    { value: 'MongoDB', label: 'MongoDB' },
    { value: 'Terraform', label: 'Terraform' },
    { value: 'Spring MVC', label: 'Spring MVC' },
    { value: 'GraphQL', label: 'GraphQL' },
    { value: 'Express.js', label: 'Express.js' },
    { value: 'Android', label: 'Android' },
    { value: 'React Native', label: 'React Native' },
    { value: 'Firebase', label: 'Firebase' },
    { value: 'Figma', label: 'Figma' },
    { value: 'Illustrator', label: 'Illustrator' },
    { value: 'Angular', label: 'Angular' }
];

export default skillOptions;
